apiVersion: v1
kind: Pod
metadata:
  name: X
  namespace: default
spec:
  hostPID: true
  containers:
  - name: honk
    image: busybox
    securityContext:
      privileged: true
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 86400; done" ]
